import { Image, StyleSheet, Text, View } from "react-native";

import {
  DEFAULT_BUSINESS_NAME,
  formatDisplayDate,
  initials,
  lineSubDescriptor,
  shortRef,
  swatchHex,
  totalQuantity,
} from "../lib/documentFormat";
import { localDateString } from "../lib/dateFormat";
import { formatMoney } from "../lib/money";
import type { BillDocumentData, StatementDocumentData } from "../repositories/documentRepository";
import { colors as docColors } from "../theme/colors";
import { theme } from "../theme/theme";

/**
 * Off-screen-rendered RN mirror of `documentFormat.ts`'s HTML bill/statement layout
 * (`design/17` / `design/17b`), captured to a PNG via `react-native-view-shot` so the
 * WhatsApp share flow can attach a real image instead of a PDF file — see `ui.md`'s
 * Sharing section. Always uses the fixed light `colors` export (never `useTheme()`), same
 * reasoning as the PDF builder and `LockScreen`: a document's look shouldn't follow the
 * device's dark/light setting.
 *
 * Fixed 720dp width — this is never shown in normal navigation, only rendered off-screen
 * for capture, so it doesn't need to fit a phone viewport like a real screen would.
 */
export const RECEIPT_IMAGE_WIDTH = 720;

function LogoTile({ logoUri, name }: { logoUri: string | null; name: string }) {
  return (
    <View style={styles.logoTile}>
      {logoUri ? (
        <Image source={{ uri: logoUri }} style={styles.logoImage} />
      ) : (
        <Text style={styles.logoInitials}>{initials(name)}</Text>
      )}
    </View>
  );
}

function DocHeader({
  logoUri,
  businessName,
  footerText,
  docType,
  docNumber,
}: {
  logoUri: string | null;
  businessName: string;
  footerText: string | null;
  docType: string;
  docNumber: string;
}) {
  return (
    <View style={styles.header}>
      <View style={styles.brandRow}>
        <LogoTile logoUri={logoUri} name={businessName} />
        <View style={styles.brandText}>
          <Text style={styles.businessName}>{businessName}</Text>
          {footerText ? <Text style={styles.businessLine}>{footerText}</Text> : null}
        </View>
      </View>
      <View style={styles.docSide}>
        <Text style={styles.docType}>{docType}</Text>
        <Text style={styles.docNumber}>#{docNumber}</Text>
      </View>
    </View>
  );
}

function PartyBox({ label, name, lines }: { label: string; name: string; lines: string[] }) {
  return (
    <View style={styles.party}>
      <Text style={styles.partyLabel}>{label}</Text>
      <Text style={styles.partyName}>{name}</Text>
      {lines.map((line, index) => (
        <Text key={index} style={styles.partyLine}>
          {line}
        </Text>
      ))}
    </View>
  );
}

function BalanceBox({
  label,
  amount,
  currency,
  tone,
}: {
  label: string;
  amount: number;
  currency: string;
  tone: "owes" | "credit" | "neutral";
}) {
  const backgroundColor =
    tone === "owes" ? docColors.owesMeSoft : tone === "credit" ? docColors.iOweSoft : docColors.surface;
  const amountColor = tone === "owes" ? docColors.owesMe : tone === "credit" ? docColors.iOwe : docColors.textPrimary;
  return (
    <View style={[styles.balanceBox, { backgroundColor }]}>
      <Text style={styles.balanceBoxLabel}>{label}</Text>
      <Text style={[styles.balanceBoxAmount, { color: amountColor }]} numberOfLines={1}>
        {formatMoney(amount, currency)}
      </Text>
    </View>
  );
}

function DocFooter({ thanksText }: { thanksText: string }) {
  return (
    <View style={styles.footer}>
      <Text style={styles.footerThanks}>{thanksText}</Text>
      <Text style={styles.footerFine}>Generated by Khata · {formatDisplayDate(localDateString())}</Text>
    </View>
  );
}

/** Mirrors `buildBillHtml()` — a single bill/receipt (`design/17`). */
export function BillReceiptImage({ data }: { data: BillDocumentData }) {
  const { settings, customer, entry } = data;
  const businessName = settings.businessName || DEFAULT_BUSINESS_NAME;
  const currency = settings.currencySymbol;
  const isCashOut = entry.direction === "cash_out";
  const itemCount = entry.type === "bill" ? totalQuantity(entry) : 1;

  return (
    <View style={styles.card}>
      <DocHeader
        logoUri={settings.logoUri}
        businessName={businessName}
        footerText={settings.billFooterText}
        docType={entry.type === "bill" ? "BILL" : "RECEIPT"}
        docNumber={shortRef(entry.id)}
      />

      <View style={styles.content}>
        <View style={styles.partiesRow}>
          <PartyBox
            label="Billed to"
            name={customer.name}
            lines={[customer.phone, customer.address].filter((v): v is string => Boolean(v))}
          />
          <PartyBox
            label="Khata reference"
            name={formatDisplayDate(entry.entryDate)}
            lines={[
              `Customer #${shortRef(customer.id)}`,
              `Last activity  ${formatDisplayDate(data.lastActivityDate)}`,
            ]}
          />
        </View>

        <View style={styles.table}>
          <View style={styles.tableHeadRow}>
            <Text style={[styles.tableHeadCell, styles.colItem]}>ITEM</Text>
            <Text style={[styles.tableHeadCell, styles.colNum]}>QTY</Text>
            <Text style={[styles.tableHeadCell, styles.colNum]}>RATE</Text>
            <Text style={[styles.tableHeadCell, styles.colNum]}>AMOUNT</Text>
          </View>
          {entry.type === "bill" ? (
            entry.lineItems.map((item) => {
              const hex = swatchHex(item.color);
              const sub = lineSubDescriptor(item);
              return (
                <View key={item.id} style={styles.tableRow}>
                  <View style={styles.colItem}>
                    <View style={styles.itemDescRow}>
                      {hex ? <View style={[styles.swatch, { backgroundColor: hex }]} /> : null}
                      <Text style={styles.itemDesc}>{item.description}</Text>
                    </View>
                    {sub ? <Text style={styles.itemSub}>{sub}</Text> : null}
                  </View>
                  <Text style={[styles.cellNum, styles.colNum]}>{item.quantity}</Text>
                  <Text style={[styles.cellNum, styles.colNum]}>{formatMoney(item.rate, currency)}</Text>
                  <Text style={[styles.cellNum, styles.colNum]}>{formatMoney(item.amount, currency)}</Text>
                </View>
              );
            })
          ) : (
            <View style={styles.tableRow}>
              <View style={styles.colItem}>
                <Text style={styles.itemDesc}>{isCashOut ? "Gave on credit" : "Payment received"}</Text>
                {entry.note ? <Text style={styles.itemSub}>{entry.note}</Text> : null}
              </View>
              <Text style={[styles.cellNum, styles.colNum]}>1</Text>
              <Text style={[styles.cellNum, styles.colNum]}>{formatMoney(entry.amount, currency)}</Text>
              <Text style={[styles.cellNum, styles.colNum]}>{formatMoney(entry.amount, currency)}</Text>
            </View>
          )}
        </View>

        <View style={styles.totalsWrap}>
          <View style={styles.note}>
            {entry.note && entry.type === "bill" ? (
              <>
                <Text style={styles.noteLabel}>NOTE</Text>
                <Text style={styles.noteText}>{entry.note}</Text>
              </>
            ) : null}
          </View>
          <View style={styles.totals}>
            <View style={styles.totalsRow}>
              <Text style={styles.muted}>
                Subtotal ({itemCount} item{itemCount === 1 ? "" : "s"})
              </Text>
              <Text>{formatMoney(entry.amount, currency)}</Text>
            </View>
            <View style={styles.billTotal}>
              <Text style={styles.billTotalLabel}>Bill total</Text>
              <Text style={styles.billTotalAmount}>{formatMoney(entry.amount, currency)}</Text>
            </View>
          </View>
        </View>

        <View style={styles.balanceSplit}>
          <BalanceBox label="Previous balance" amount={data.previousBalance} currency={currency} tone="neutral" />
          <BalanceBox
            label="Balance owed"
            amount={data.currentBalance}
            currency={currency}
            tone={data.currentBalance > 0 ? "owes" : data.currentBalance < 0 ? "credit" : "neutral"}
          />
        </View>

        <DocFooter thanksText={settings.billFooterText || "Thank you for shopping with us!"} />
      </View>
    </View>
  );
}

/** Mirrors `buildStatementHtml()` — a full customer ledger statement (`design/17b`). */
export function StatementReceiptImage({ data }: { data: StatementDocumentData }) {
  const { settings, customer, rows } = data;
  const businessName = settings.businessName || DEFAULT_BUSINESS_NAME;
  const currency = settings.currencySymbol;

  const periodStart = formatDisplayDate(data.dateFrom ?? data.openingBalanceDate);
  const periodEnd = formatDisplayDate(data.dateTo ?? data.generatedAt);
  const entriesLabel = `${rows.length} ${rows.length === 1 ? "entry" : "entries"}`;

  const openingIsDebit = data.openingBalance > 0;
  const openingDebit = openingIsDebit ? data.openingBalance : 0;
  const openingCredit = !openingIsDebit && data.openingBalance < 0 ? -data.openingBalance : 0;

  const debitTotal =
    openingDebit +
    rows.filter((r) => r.entry.direction === "cash_out").reduce((sum, r) => sum + r.entry.amount, 0);
  const creditTotal =
    openingCredit +
    rows.filter((r) => r.entry.direction === "cash_in").reduce((sum, r) => sum + r.entry.amount, 0);

  return (
    <View style={styles.card}>
      <DocHeader
        logoUri={settings.logoUri}
        businessName={businessName}
        footerText={settings.billFooterText}
        docType="LEDGER STATEMENT"
        docNumber={shortRef(customer.id, "KH-LS-")}
      />

      <View style={styles.content}>
        <View style={styles.partiesRow}>
          <PartyBox
            label="Account"
            name={customer.name}
            lines={customer.phone ? [customer.phone] : []}
          />
          <PartyBox label="Statement period" name={`${periodStart} – ${periodEnd}`} lines={[entriesLabel]} />
        </View>

        <View style={styles.table}>
          <View style={styles.tableHeadRow}>
            <Text style={[styles.tableHeadCell, styles.colDate]}>DATE</Text>
            <Text style={[styles.tableHeadCell, styles.colDesc]}>DESCRIPTION</Text>
            <Text style={[styles.tableHeadCell, styles.colNum]}>DEBIT</Text>
            <Text style={[styles.tableHeadCell, styles.colNum]}>CREDIT</Text>
            <Text style={[styles.tableHeadCell, styles.colNum]}>BALANCE</Text>
          </View>
          <View style={styles.tableRow}>
            <Text style={[styles.cellText, styles.colDate]}>{formatDisplayDate(data.openingBalanceDate)}</Text>
            <Text style={[styles.cellText, styles.colDesc]}>Opening balance</Text>
            <Text style={[styles.cellNum, styles.colNum, styles.owesText]}>
              {openingDebit > 0 ? formatMoney(openingDebit, currency) : "—"}
            </Text>
            <Text style={[styles.cellNum, styles.colNum, styles.creditText]}>
              {openingCredit > 0 ? formatMoney(openingCredit, currency) : "—"}
            </Text>
            <Text style={[styles.cellNum, styles.colNum]}>{formatMoney(data.openingBalance, currency)}</Text>
          </View>
          {rows.map((row) => {
            const isCashOut = row.entry.direction === "cash_out";
            const label =
              row.entry.type === "bill"
                ? `Bill · ${row.entry.lineItems.length} item${row.entry.lineItems.length === 1 ? "" : "s"}`
                : isCashOut
                  ? "Cash given"
                  : "Cash payment";
            return (
              <View key={row.entry.id} style={styles.tableRow}>
                <Text style={[styles.cellText, styles.colDate]}>{formatDisplayDate(row.entry.entryDate)}</Text>
                <Text style={[styles.cellText, styles.colDesc]}>{label}</Text>
                <Text style={[styles.cellNum, styles.colNum, styles.owesText]}>
                  {isCashOut ? formatMoney(row.entry.amount, currency) : "—"}
                </Text>
                <Text style={[styles.cellNum, styles.colNum, styles.creditText]}>
                  {!isCashOut ? formatMoney(row.entry.amount, currency) : "—"}
                </Text>
                <Text style={[styles.cellNum, styles.colNum]}>{formatMoney(row.runningBalance, currency)}</Text>
              </View>
            );
          })}
        </View>

        <View style={styles.balanceSplit}>
          <BalanceBox label="Total debits" amount={debitTotal} currency={currency} tone="owes" />
          <BalanceBox label="Total credits" amount={creditTotal} currency={currency} tone="credit" />
        </View>
        <View style={[styles.billTotal, styles.closingBalance]}>
          <Text style={styles.billTotalLabel}>Closing balance owed</Text>
          <Text style={styles.billTotalAmount}>{formatMoney(data.currentBalance, currency)}</Text>
        </View>

        <DocFooter thanksText={settings.billFooterText || "Please clear dues at your earliest convenience."} />
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  card: {
    width: RECEIPT_IMAGE_WIDTH,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: docColors.border,
    borderRadius: theme.radius.lg,
    overflow: "hidden",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: theme.spacing.md,
    backgroundColor: docColors.primary,
    padding: theme.spacing.lg,
  },
  brandRow: {
    flexDirection: "row",
    gap: theme.spacing.md,
    alignItems: "flex-start",
    flexShrink: 1,
  },
  logoTile: {
    width: 68,
    height: 68,
    borderRadius: theme.radius.md,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  logoImage: {
    width: "100%",
    height: "100%",
  },
  logoInitials: {
    fontWeight: "700",
    color: docColors.primary,
    fontSize: 22,
  },
  brandText: {
    flexShrink: 1,
  },
  businessName: {
    fontSize: 26,
    fontWeight: "700",
    color: "#fff",
  },
  businessLine: {
    color: docColors.primaryMuted,
    marginTop: 5,
    fontSize: 14,
  },
  docSide: {
    alignItems: "flex-end",
  },
  docType: {
    color: docColors.accent,
    letterSpacing: 2,
    fontWeight: "700",
    fontSize: 13,
    textTransform: "uppercase",
  },
  docNumber: {
    fontSize: 22,
    fontWeight: "700",
    marginTop: 5,
    color: "#fff",
  },
  content: {
    padding: theme.spacing.lg,
  },
  muted: {
    color: docColors.textSecondary,
  },
  partiesRow: {
    flexDirection: "row",
    gap: theme.spacing.md,
  },
  party: {
    flex: 1,
    backgroundColor: docColors.surface,
    borderRadius: theme.radius.md,
    padding: theme.spacing.md,
  },
  partyLabel: {
    color: docColors.textSecondary,
    letterSpacing: 1,
    fontSize: 12,
    fontWeight: "700",
    marginBottom: theme.spacing.xs,
    textTransform: "uppercase",
  },
  partyName: {
    fontWeight: "700",
    fontSize: 18,
    color: docColors.textPrimary,
  },
  partyLine: {
    color: docColors.textSecondary,
    marginTop: 4,
    fontSize: 14,
  },
  table: {
    marginTop: theme.spacing.lg,
    borderRadius: theme.radius.md,
    overflow: "hidden",
  },
  tableHeadRow: {
    flexDirection: "row",
    backgroundColor: docColors.primary,
  },
  tableHeadCell: {
    color: "#fff",
    fontSize: 12,
    letterSpacing: 1,
    textTransform: "uppercase",
    fontWeight: "700",
    paddingVertical: 13,
    paddingHorizontal: theme.spacing.md,
  },
  tableRow: {
    flexDirection: "row",
    padding: theme.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: docColors.border,
  },
  colItem: {
    flex: 3,
  },
  colDate: {
    flex: 1.4,
  },
  colDesc: {
    flex: 2.4,
  },
  colNum: {
    flex: 1,
    textAlign: "right",
  },
  cellText: {
    fontSize: 15,
    color: docColors.textPrimary,
  },
  cellNum: {
    fontSize: 15,
    color: docColors.textPrimary,
  },
  itemDescRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  itemDesc: {
    fontWeight: "700",
    fontSize: 15,
    color: docColors.textPrimary,
  },
  itemSub: {
    color: docColors.textSecondary,
    marginTop: 4,
    fontSize: 13,
  },
  swatch: {
    width: 13,
    height: 13,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: docColors.border,
    marginEnd: 7,
  },
  owesText: {
    color: docColors.owesMe,
  },
  creditText: {
    color: docColors.iOwe,
  },
  totalsWrap: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: theme.spacing.lg,
    gap: theme.spacing.lg,
  },
  note: {
    flex: 1,
  },
  noteLabel: {
    color: docColors.textSecondary,
    fontSize: 12,
    letterSpacing: 1,
    fontWeight: "700",
    textTransform: "uppercase",
    marginBottom: 5,
  },
  noteText: {
    color: docColors.textSecondary,
    lineHeight: 20,
    fontSize: 14,
  },
  totals: {
    width: 280,
  },
  totalsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: theme.spacing.xs,
  },
  billTotal: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: docColors.primary,
    paddingVertical: theme.spacing.md,
    paddingHorizontal: theme.spacing.md,
    borderRadius: theme.radius.md,
    marginTop: theme.spacing.xs,
  },
  billTotalLabel: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 20,
  },
  billTotalAmount: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 20,
  },
  closingBalance: {
    marginTop: theme.spacing.md,
  },
  balanceSplit: {
    flexDirection: "row",
    gap: theme.spacing.sm,
    marginTop: theme.spacing.md,
  },
  balanceBox: {
    flex: 1,
    borderRadius: theme.radius.md,
    padding: theme.spacing.md,
  },
  balanceBoxLabel: {
    color: docColors.textSecondary,
    fontSize: 13,
    marginBottom: 5,
  },
  balanceBoxAmount: {
    fontWeight: "700",
    fontSize: 22,
  },
  footer: {
    marginTop: theme.spacing.lg,
    borderTopWidth: 1,
    borderTopColor: docColors.border,
    paddingTop: theme.spacing.md,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    gap: theme.spacing.md,
  },
  footerThanks: {
    fontWeight: "600",
    fontStyle: "italic",
    fontSize: 15,
    color: docColors.textPrimary,
    flexShrink: 1,
  },
  footerFine: {
    color: docColors.textSecondary,
    fontSize: 12,
  },
});
